// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDakebJtojIGMp2ByK1LYWBViw74pCmVdg',
    appId: '1:737373835066:web:530398e80be116f49d0a03',
    messagingSenderId: '737373835066',
    projectId: 'edlink-41098',
    authDomain: 'edlink-41098.firebaseapp.com',
    storageBucket: 'edlink-41098.firebasestorage.app',
    measurementId: 'G-L7Q9Q7T3Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChupHKsRDvoGiBngVNip8tvO7Bsl-uJjE',
    appId: '1:737373835066:android:356aaf3a2eaeaf459d0a03',
    messagingSenderId: '737373835066',
    projectId: 'edlink-41098',
    storageBucket: 'edlink-41098.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDinfXkpz7IU7oodGXyTBiG5kb9lzhPfs',
    appId: '1:737373835066:ios:05650097315635839d0a03',
    messagingSenderId: '737373835066',
    projectId: 'edlink-41098',
    storageBucket: 'edlink-41098.firebasestorage.app',
    iosClientId: '737373835066-tcim4hisvnq15op6i3b150v6h3pq42r0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubasPabDeyayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDinfXkpz7IU7oodGXyTBiG5kb9lzhPfs',
    appId: '1:737373835066:ios:05650097315635839d0a03',
    messagingSenderId: '737373835066',
    projectId: 'edlink-41098',
    storageBucket: 'edlink-41098.firebasestorage.app',
    iosClientId: '737373835066-tcim4hisvnq15op6i3b150v6h3pq42r0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubasPabDeyayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDakebJtojIGMp2ByK1LYWBViw74pCmVdg',
    appId: '1:737373835066:web:67fe59c61ad12b8d9d0a03',
    messagingSenderId: '737373835066',
    projectId: 'edlink-41098',
    authDomain: 'edlink-41098.firebaseapp.com',
    storageBucket: 'edlink-41098.firebasestorage.app',
    measurementId: 'G-TRZYKJTNV3',
  );
}
